# Generated by Django 3.2.6 on 2021-08-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, default=0)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('bmi', models.FloatField(blank=True, default=0)),
                ('bmr', models.FloatField(blank=True, default=0)),
                ('water_demand', models.FloatField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, default=0)),
                ('calf', models.FloatField(blank=True, default=0)),
                ('thigh', models.FloatField(blank=True, default=0)),
                ('hips', models.FloatField(blank=True, default=0)),
                ('waist', models.FloatField(blank=True, default=0)),
                ('chest', models.FloatField(blank=True, default=0)),
                ('neck', models.FloatField(blank=True, default=0)),
                ('biceps', models.FloatField(blank=True, default=0)),
                ('forearm', models.FloatField(blank=True, default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
