# Generated by Django 3.2.6 on 2021-08-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meals_names', models.TextField(blank=True, default='')),
                ('total_calories', models.FloatField(blank=True, default=0)),
                ('total_sugar', models.FloatField(blank=True, default=0)),
                ('total_protein', models.FloatField(blank=True, default=0)),
                ('total_fiber', models.FloatField(blank=True, default=0)),
                ('total_potassium_mg', models.FloatField(blank=True, default=0)),
                ('total_sodium_mg', models.FloatField(blank=True, default=0)),
                ('total_fat_saturated', models.FloatField(blank=True, default=0)),
                ('total_fat', models.FloatField(blank=True, default=0)),
                ('total_carbohydrates', models.FloatField(blank=True, default=0)),
                ('total_cholesterol_mg', models.FloatField(blank=True, default=0)),
                ('user_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
