# Generated by Django 3.2.6 on 2021-08-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMacros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(blank=True, default=0)),
                ('sugar', models.FloatField(blank=True, default=0)),
                ('protein', models.FloatField(blank=True, default=0)),
                ('fiber', models.FloatField(blank=True, default=0)),
                ('potassium_mg', models.FloatField(blank=True, default=0)),
                ('sodium_mg', models.FloatField(blank=True, default=0)),
                ('fat_saturated', models.FloatField(blank=True, default=0)),
                ('fat', models.FloatField(blank=True, default=0)),
                ('carbohydrates', models.FloatField(blank=True, default=0)),
                ('cholesterol_mg', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('category', models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SNACK', 'snack'), ('OTHER', 'other')], max_length=9)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ingredients', models.TextField()),
                ('macros', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemacros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
